[tool.mypy]
# Ignoring missing imports generally
ignore_missing_imports = true

# Optionally exclude specific directories or files
exclude = "django_celery_beat/models"

# Disallow untyped calls and definitions
disallow_untyped_calls = true
disallow_untyped_defs = true

# Warning options
warn_return_any = true
warn_unused_ignores = true

# Plugins for Django
plugins = ["mypy_django_plugin.main"]

# Additional configuration for the plugin
[tool.django-stubs]
django_settings_module = "lunch_voting.settings.dev"
