# Generated by Django 5.0 on 2024-08-27 17:09

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0002_voting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voting",
            name="date",
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.CreateModel(
            name="VotingHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=datetime.datetime.today,
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="voting.restaurant",
                    ),
                ),
            ],
        ),
    ]
