# Generated by Django 5.0 on 2024-08-27 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0003_alter_voting_date_votinghistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voting",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
