# Generated by Django 5.0 on 2024-08-27 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0004_alter_voting_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="votinghistory",
            name="date",
            field=models.DateField(
                default=datetime.date.today,
            ),
        ),
    ]
