# Generated by Django 5.0 on 2024-08-28 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0005_alter_votinghistory_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="VotingLocker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("voting_locked", models.BooleanField(default=False)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
